### ISSUE TITLE
Post Update 

### ISSUE THREAD

**Issue by serkaneo** [furkancelik/graphql-boilerplate#2]
Selam Furkan
Post Update işlemini ekleyebilir misin?
çok teşekkür ederim.

**Comment by furkancelik** [comment]
Post Update derken?
File upload işlemlerinden mi bahsediyorsun?

**Comment by serkaneo** [comment]
updatePost mutation resolver işlemi. güncelleme işlemi
![2019-10-15_20-59-46](https://user-images.githubusercontent.com/52151765/66857083-34ff0200-ef8f-11e9-8930-573a4f6fed65.png)

**Comment by furkancelik** [comment]
c922ba48706216a8caa82388cf3304b09f6f767a bir commit gönderdim.
